// Code generated by slimgen. DO NOT EDIT.

package slim

import "github.com/praetorian-inc/tabularium/pkg/model/model"

// SlimPort is a simplified Port for external tool writers.
type SlimPort struct {
	Asset SlimAsset `json:"-"`
	// The protocol of this port.
	Protocol string `json:"protocol"`
	// The port number of this port.
	Port int `json:"port"`
	// The name of the service identified on this port.
	Service string `json:"service"`
	// Capability that discovered this port.
	Capability string `json:"capability,omitempty"`
}

func (SlimPort) TargetModel() string { return "port" }

// GetParentAsset returns the embedded parent asset for SlimPort.
func (s SlimPort) GetParentAsset() SlimAsset { return s.Asset }

func (SlimPort) injectParent() {}

// SlimRisk is a simplified Risk for external tool writers.
type SlimRisk struct {
	// Primary DNS or group associated with the risk.
	DNS string `json:"dns"`
	// Name of the risk or vulnerability.
	Name string `json:"name"`
	// User-provided comment about the risk.
	Comment string `json:"comment,omitempty"`
}

func (SlimRisk) TargetModel() string { return "risk" }

// SlimTechnology is a simplified Technology for external tool writers.
type SlimTechnology struct {
	// The full CPE string representation.
	CPE string `json:"cpe"`
	// Optional common name for the technology.
	Name string `json:"name,omitempty"`
	// User-provided comment about the technology record.
	Comment string `json:"comment,omitempty"`
}

func (SlimTechnology) TargetModel() string { return "technology" }

// SlimAttribute is a simplified Attribute for external tool writers.
type SlimAttribute struct {
	Asset SlimAsset `json:"-"`
	// Name of the attribute.
	Name string `json:"name"`
	// Value of the attribute.
	Value string `json:"value"`
	// Capability that discovered this attribute.
	Capability string `json:"capability,omitempty"`
	// Additional metadata associated with the attribute.
	Metadata map[string]string `json:"metadata,omitempty"`
}

func (SlimAttribute) TargetModel() string { return "attribute" }

// GetParentAsset returns the embedded parent asset for SlimAttribute.
func (s SlimAttribute) GetParentAsset() SlimAsset { return s.Asset }

func (SlimAttribute) injectParent() {}

// SlimFile is a simplified File for external tool writers.
type SlimFile struct {
	// Name or path of the file.
	Name string `json:"name"`
	// File content. Must be a JSON-compatible string. Can be encoded with base64 if it begins with the prefix 'base64:'
	Bytes model.SmartBytes `json:"bytes"`
}

func (SlimFile) TargetModel() string { return "file" }

// SlimWebpage is a simplified Webpage for external tool writers.
type SlimWebpage struct {
	Asset SlimAsset `json:"-"`
	// The basic URL of the webpage.
	URL string `json:"url"`
}

func (SlimWebpage) TargetModel() string { return "webpage" }

// GetParentAsset returns the embedded parent asset for SlimWebpage.
func (s SlimWebpage) GetParentAsset() SlimAsset { return s.Asset }

// SlimWebApplication is a simplified WebApplication for external tool writers.
type SlimWebApplication struct {
	// The primary/canonical URL of the web application
	PrimaryURL string `json:"primary_url"`
	// Additional URLs associated with this web application
	URLs []string `json:"urls"`
	// Name of the web application
	Name string `json:"name"`
}

func (SlimWebApplication) TargetModel() string { return "webapplication" }
