// Code generated by slimgen. DO NOT EDIT.

package slim

import "github.com/praetorian-inc/tabularium/pkg/model/model"

// SlimPort is a simplified Port for external tool writers.
type SlimPort struct {
	Asset    SlimAsset `json:"-"`
	Protocol string    `json:"protocol"`
	Port     int       `json:"port"`
	Service  string    `json:"service"`
	// Capability is the name of the scanner or tool that discovered this port.
	Capability string `json:"capability,omitempty"`
}

func (SlimPort) TargetModel() string { return "port" }

// GetParentAsset returns the embedded parent asset for SlimPort.
func (s SlimPort) GetParentAsset() SlimAsset { return s.Asset }

func (SlimPort) injectParent() {}

// SlimRisk is a simplified Risk for external tool writers.
type SlimRisk struct {
	// DNS is the grouping domain or identifier the risk is associated with.
	DNS string `json:"dns"`
	// Name is the vulnerability identifier (e.g. CVE-2024-1234). Non-CVE names are automatically lowercased and spaces replaced with dashes.
	Name    string `json:"name"`
	Comment string `json:"comment,omitempty"`
}

func (SlimRisk) TargetModel() string { return "risk" }

// SlimTechnology is a simplified Technology for external tool writers.
type SlimTechnology struct {
	CPE     string `json:"cpe"`
	Name    string `json:"name,omitempty"`
	Comment string `json:"comment,omitempty"`
}

func (SlimTechnology) TargetModel() string { return "technology" }

// SlimAttribute is a simplified Attribute for external tool writers.
type SlimAttribute struct {
	Asset SlimAsset `json:"-"`
	Name  string    `json:"name"`
	Value string    `json:"value"`
	// Capability is the name of the scanner or tool that discovered this attribute.
	Capability string `json:"capability,omitempty"`
	// Metadata is an optional set of freeform key-value pairs.
	Metadata map[string]string `json:"metadata,omitempty"`
}

func (SlimAttribute) TargetModel() string { return "attribute" }

// GetParentAsset returns the embedded parent asset for SlimAttribute.
func (s SlimAttribute) GetParentAsset() SlimAsset { return s.Asset }

func (SlimAttribute) injectParent() {}

// SlimFile is a simplified File for external tool writers.
type SlimFile struct {
	Name string `json:"name"`
	// Bytes is the file content. Pass a plain []byte value.
	Bytes model.SmartBytes `json:"bytes"`
}

func (SlimFile) TargetModel() string { return "file" }

// SlimWebpage is a simplified Webpage for external tool writers.
type SlimWebpage struct {
	Asset SlimAsset `json:"-"`
	URL   string    `json:"url"`
}

func (SlimWebpage) TargetModel() string { return "webpage" }

// GetParentAsset returns the embedded parent asset for SlimWebpage.
func (s SlimWebpage) GetParentAsset() SlimAsset { return s.Asset }

// SlimWebApplication is a simplified WebApplication for external tool writers.
type SlimWebApplication struct {
	PrimaryURL string   `json:"primary_url"`
	URLs       []string `json:"urls"`
	Name       string   `json:"name"`
}

func (SlimWebApplication) TargetModel() string { return "webapplication" }
