// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

type AzureResource struct {
	IPs           []string       `json:"ips"`
	URLs          []string       `json:"urls"`
	Name          string         `json:"name"`
	ResourceType  string         `json:"resourceType"`
	Region        string         `json:"region"`
	AccountRef    string         `json:"accountRef"`
	Properties    map[string]any `json:"properties"`
	ResourceGroup string         `json:"resourceGroup"`
}

func (s AzureResource) Convert() (*model.AzureResource, error) {
	m := make(map[string]any, 8)
	m["ips"] = s.IPs
	m["urls"] = s.URLs
	m["name"] = s.Name
	m["resourceType"] = s.ResourceType
	m["region"] = s.Region
	m["accountRef"] = s.AccountRef
	m["properties"] = s.Properties
	m["resourceGroup"] = s.ResourceGroup

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.AzureResource
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}
