// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

type IP struct {
	DNS string `json:"ip"`
}

func (s IP) Convert() (*model.Asset, error) {
	m := make(map[string]any, 1)
	m["dns"] = s.DNS
	m["name"] = s.DNS

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Asset
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}
