// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

type Port struct {
	Protocol string `json:"protocol"`
	Port     int    `json:"port"`
	Service  string `json:"service"`
	Parent   Asset  `json:"parent"`
}
