// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

type Preseed struct {
	Type  string `json:"type"`
	Title string `json:"title"`
	Value string `json:"value"`
}

func (s Preseed) Convert() (*model.Preseed, error) {
	m := make(map[string]any, 3)
	m["type"] = s.Type
	m["title"] = s.Title
	m["value"] = s.Value

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Preseed
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}
