// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

type Risk struct {
	DNS    string `json:"dns"`
	Name   string `json:"name"`
	Source string `json:"source"`
	Status string `json:"status"`
	Target Asset  `json:"target"`
}

func (s Risk) Convert() (*model.Risk, error) {
	m := make(map[string]any, 4)
	m["dns"] = s.DNS
	m["name"] = s.Name
	m["source"] = s.Source
	m["status"] = s.Status
	parentModel, err := s.Target.Convert()
	if err != nil {
		return nil, err
	}

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Risk
	result.Defaulted()
	if err := json.Unmarshal(b, &result); err != nil {
		return nil, err
	}
	result.Target = parentModel
	if err := registry.CallHooks(&result); err != nil {
		return nil, err
	}

	return &result, nil
}
