// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

type Technology struct {
	CPE  string `json:"cpe"`
	Name string `json:"name"`
}

func (s Technology) Convert() (*model.Technology, error) {
	m := make(map[string]any, 2)
	m["cpe"] = s.CPE
	m["name"] = s.Name

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Technology
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}
