// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

type WebApplication struct {
	PrimaryURL string   `json:"primary_url"`
	URLs       []string `json:"urls"`
	Name       string   `json:"name"`
}
