package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"text/template"
)

const generatedHeader = `// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)
`

func generate(slimTypes []slimType, outputDir string) error {
	sort.Slice(slimTypes, func(i, j int) bool {
		return slimTypes[i].Name < slimTypes[j].Name
	})

	var buf bytes.Buffer
	buf.WriteString(generatedHeader)

	for _, st := range slimTypes {
		if err := typeTmpl.Execute(&buf, st); err != nil {
			return fmt.Errorf("generating %s: %w", st.Name, err)
		}
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		debugPath := filepath.Join(outputDir, "generated_debug.go")
		if writeErr := os.WriteFile(debugPath, buf.Bytes(), 0644); writeErr != nil {
			return fmt.Errorf("formatting generated code: %w (also failed to write debug: %v)", err, writeErr)
		}
		return fmt.Errorf("formatting generated code: %w (debug written to %s)", err, debugPath)
	}

	outPath := filepath.Join(outputDir, "generated.go")
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return err
	}
	return os.WriteFile(outPath, formatted, 0644)
}

// manualUnmarshal is true when the parent must be set before hooks run,
// requiring manual Defaulted + Unmarshal + CallHooks instead of UnmarshalModel.
func manualUnmarshal(p *parentField) bool {
	return p != nil && p.Kind != parentInterface
}

var typeTmpl = template.Must(template.New("type").Funcs(template.FuncMap{
	"eq":              func(a, b parentKind) bool { return a == b },
	"manualUnmarshal": manualUnmarshal,
}).Parse(`
type {{.Name}} struct {
{{- range .Fields}}
	{{.SourceFieldName}} {{.GoType}} ` + "`" + `json:"{{.JSONName}}"` + "`" + `
{{- end}}
{{- if .Parent}}
	{{.Parent.SourceFieldName}} {{.Parent.SlimType}} ` + "`" + `json:"{{.Parent.JSONName}}"` + "`" + `
{{- end}}
}

func (s {{.Name}}) Convert() (*model.{{.SourceTypeName}}, error) {
	m := make(map[string]any)
{{- range $f := .Fields}}
{{- range $f.SourceJSONNames}}
	m["{{.}}"] = s.{{$f.SourceFieldName}}
{{- end}}
{{- end}}
{{- if .Parent}}
	parentModel, err := s.{{.Parent.SourceFieldName}}.Convert()
	if err != nil {
		return nil, err
	}
{{- end}}

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.{{.SourceTypeName}}
{{- if manualUnmarshal .Parent}}
	result.Defaulted()
	if err := json.Unmarshal(b, &result); err != nil {
		return nil, err
	}
{{- if eq .Parent.Kind "inject"}}
	result.{{.Parent.SourceFieldName}} = model.NewGraphModelWrapper(parentModel)
{{- else}}
	result.{{.Parent.SourceFieldName}} = parentModel
{{- end}}
	if err := registry.CallHooks(&result); err != nil {
		return nil, err
	}
{{- else}}
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}
{{- if .Parent}}
	result.{{.Parent.SourceFieldName}} = parentModel
{{- end}}
{{- end}}

	return &result, nil
}
`))
