// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

type ADObject struct {
	Label           string         `json:"label"`
	SecondaryLabels []string       `json:"labels"`
	Domain          string         `json:"domain"`
	ObjectID        string         `json:"objectid"`
	SID             string         `json:"sid"`
	ADProperties    map[string]any `json:"properties"`
}

func (s ADObject) Convert() (*model.ADObject, error) {
	m := make(map[string]any)
	m["label"] = s.Label
	m["labels"] = s.SecondaryLabels
	m["domain"] = s.Domain
	m["objectid"] = s.ObjectID
	m["sid"] = s.SID
	for k, v := range s.ADProperties {
		m[k] = v
	}

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.ADObject
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}
