// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

type Asset struct {
	DNS  string `json:"dns"`
	Name string `json:"name"`
}

func (s Asset) Convert() (*model.Asset, error) {
	m := make(map[string]any, 2)
	m["dns"] = s.DNS
	m["name"] = s.Name

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Asset
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}
