// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"
	"fmt"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

func init() {
	registry.Registry.MustRegisterConverter("ADObject", convertADObject)
	registry.Registry.MustRegisterConverter("AWSResource", convertAWSResource)
	registry.Registry.MustRegisterConverter("Asset", convertAsset)
	registry.Registry.MustRegisterConverter("AzureResource", convertAzureResource)
	registry.Registry.MustRegisterConverter("Domain", convertDomain)
	registry.Registry.MustRegisterConverter("File", convertFile)
	registry.Registry.MustRegisterConverter("GCPResource", convertGCPResource)
	registry.Registry.MustRegisterConverter("IP", convertIP)
	registry.Registry.MustRegisterConverter("Organization", convertOrganization)
	registry.Registry.MustRegisterConverter("Person", convertPerson)
	registry.Registry.MustRegisterConverter("Port", convertPort)
	registry.Registry.MustRegisterConverter("Preseed", convertPreseed)
	registry.Registry.MustRegisterConverter("Repository", convertRepository)
	registry.Registry.MustRegisterConverter("Risk", convertRisk)
	registry.Registry.MustRegisterConverter("Technology", convertTechnology)
	registry.Registry.MustRegisterConverter("WebApplication", convertWebApplication)
	registry.Registry.MustRegisterConverter("Webpage", convertWebpage)
}

func convertADObject(data []byte) (registry.Model, error) {
	var result model.ADObject
	if err := registry.UnmarshalModel(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertAWSResource(data []byte) (registry.Model, error) {
	var result model.AWSResource
	if err := registry.UnmarshalModel(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertAsset(data []byte) (registry.Model, error) {
	var result model.Asset
	if err := registry.UnmarshalModel(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertAzureResource(data []byte) (registry.Model, error) {
	var result model.AzureResource
	if err := registry.UnmarshalModel(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertDomain(data []byte) (registry.Model, error) {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	if v, ok := raw["domain"]; ok {
		delete(raw, "domain")
		raw["dns"] = v
		raw["name"] = v
	}
	b, err := json.Marshal(raw)
	if err != nil {
		return nil, err
	}
	var result model.Asset
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertFile(data []byte) (registry.Model, error) {
	var result model.File
	if err := registry.UnmarshalModel(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertGCPResource(data []byte) (registry.Model, error) {
	var result model.GCPResource
	if err := registry.UnmarshalModel(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertIP(data []byte) (registry.Model, error) {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	if v, ok := raw["ip"]; ok {
		delete(raw, "ip")
		raw["dns"] = v
		raw["name"] = v
	}
	b, err := json.Marshal(raw)
	if err != nil {
		return nil, err
	}
	var result model.Asset
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertOrganization(data []byte) (registry.Model, error) {
	var result model.Organization
	if err := registry.UnmarshalModel(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertPerson(data []byte) (registry.Model, error) {
	var result model.Person
	if err := registry.UnmarshalModel(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertPort(data []byte) (registry.Model, error) {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	parentRaw := raw["parent"]
	delete(raw, "parent")
	b, err := json.Marshal(raw)
	if err != nil {
		return nil, err
	}
	var parentModel registry.Model
	if parentRaw != nil {
		parentModel, err = registry.Registry.Convert("Asset", parentRaw)
		if err != nil {
			return nil, err
		}
	}
	var result model.Port
	result.Defaulted()
	if err := json.Unmarshal(b, &result); err != nil {
		return nil, err
	}
	if parentModel != nil {
		gm, ok := parentModel.(model.GraphModel)
		if !ok {
			return nil, fmt.Errorf("convertPort: parent is %T, not model.GraphModel", parentModel)
		}
		result.Parent = model.NewGraphModelWrapper(gm)
	}
	if err := registry.CallHooks(&result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertPreseed(data []byte) (registry.Model, error) {
	var result model.Preseed
	if err := registry.UnmarshalModel(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertRepository(data []byte) (registry.Model, error) {
	var result model.Repository
	if err := registry.UnmarshalModel(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertRisk(data []byte) (registry.Model, error) {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	if v, ok := raw["proof"]; ok {
		delete(raw, "proof")
		raw["sdkproof"] = v
	}
	parentRaw := raw["target"]
	delete(raw, "target")
	b, err := json.Marshal(raw)
	if err != nil {
		return nil, err
	}
	var parentModel registry.Model
	if parentRaw != nil {
		parentModel, err = registry.Registry.Convert("Asset", parentRaw)
		if err != nil {
			return nil, err
		}
	}
	var result model.Risk
	result.Defaulted()
	if err := json.Unmarshal(b, &result); err != nil {
		return nil, err
	}
	if parentModel != nil {
		typed, ok := parentModel.(model.Target)
		if !ok {
			return nil, fmt.Errorf("convertRisk: parent is %T, not model.Target", parentModel)
		}
		result.Target = typed
	}
	if err := registry.CallHooks(&result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertTechnology(data []byte) (registry.Model, error) {
	var result model.Technology
	if err := registry.UnmarshalModel(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertWebApplication(data []byte) (registry.Model, error) {
	var result model.WebApplication
	if err := registry.UnmarshalModel(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func convertWebpage(data []byte) (registry.Model, error) {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	parentRaw := raw["parent"]
	delete(raw, "parent")
	b, err := json.Marshal(raw)
	if err != nil {
		return nil, err
	}
	var parentModel registry.Model
	if parentRaw != nil {
		parentModel, err = registry.Registry.Convert("WebApplication", parentRaw)
		if err != nil {
			return nil, err
		}
	}
	var result model.Webpage
	result.Defaulted()
	if err := json.Unmarshal(b, &result); err != nil {
		return nil, err
	}
	if parentModel != nil {
		typed, ok := parentModel.(*model.WebApplication)
		if !ok {
			return nil, fmt.Errorf("convertWebpage: parent is %T, not *model.WebApplication", parentModel)
		}
		result.Parent = typed
	}
	if err := registry.CallHooks(&result); err != nil {
		return nil, err
	}
	return &result, nil
}
