// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

type File struct {
	Name  string `json:"name"`
	Bytes []byte `json:"bytes"`
}

func (s File) Convert() (*model.File, error) {
	m := make(map[string]any)
	m["name"] = s.Name
	m["bytes"] = s.Bytes

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.File
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}
