// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

type GCPResource struct {
	IPs          []string       `json:"ips"`
	URLs         []string       `json:"urls"`
	Name         string         `json:"name"`
	ResourceType string         `json:"resourceType"`
	Region       string         `json:"region"`
	AccountRef   string         `json:"accountRef"`
	Properties   map[string]any `json:"properties"`
}

func (s GCPResource) Convert() (*model.GCPResource, error) {
	m := make(map[string]any, 7)
	m["ips"] = s.IPs
	m["urls"] = s.URLs
	m["name"] = s.Name
	m["resourceType"] = s.ResourceType
	m["region"] = s.Region
	m["accountRef"] = s.AccountRef
	m["properties"] = s.Properties

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.GCPResource
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}
