// Code generated by capmodelgen. DO NOT EDIT.

package capmodel

// WebApplication is a capability model for WebApplication.
type WebApplication struct {
	// The primary/canonical URL of the web application
	PrimaryURL string `json:"primary_url"`
	// Additional URLs associated with this web application
	URLs []string `json:"urls"`
	// Name of the web application
	Name string `json:"name"`
}

func (WebApplication) TargetModel() string { return "webapplication" }
