// Code generated by capmodelgen. DO NOT EDIT.

package capmodel

// Person is a capability model for Person.
type Person struct {
	// Person's first name.
	FirstName *string `json:"first_name,omitempty"`
	// Person's last name.
	LastName *string `json:"last_name,omitempty"`
	// Person's full name.
	Name *string `json:"name,omitempty"`
	// Person's primary email address.
	Email *string `json:"email,omitempty"`
	// Person's current job title.
	Title *string `json:"title,omitempty"`
	// Person's professional headline.
	Headline *string `json:"headline,omitempty"`
	// Person's phone number.
	Phone *string `json:"phone,omitempty"`
	// List of personal email addresses.
	PersonalEmails *[]string `json:"personal_emails,omitempty"`
	// Person's work email address.
	WorkEmail *string `json:"work_email,omitempty"`
	// LinkedIn profile URL.
	LinkedinURL *string `json:"linkedin_url,omitempty"`
	// GitHub profile URL.
	GithubURL *string `json:"github_url,omitempty"`
	// Name of organization where person currently works.
	OrganizationName *string `json:"organization_name,omitempty"`
	// Email verification status.
	EmailStatus *string `json:"email_status,omitempty"`
	// Country where the person is located.
	Country *string `json:"country,omitempty"`
	// State or region where the person is located.
	State *string `json:"state,omitempty"`
	// City where the person is located.
	City *string `json:"city,omitempty"`
	// Seniority level.
	Seniority *string `json:"seniority,omitempty"`
	// List of departments person works in.
	Departments *[]string `json:"departments,omitempty"`
}

func (Person) TargetModel() string { return "person" }
