// Code generated by capmodelgen. DO NOT EDIT.

package capmodel

// Organization is a capability model for Organization.
type Organization struct {
	// Organization name.
	Name *string `json:"name,omitempty"`
	// Primary domain associated with the organization.
	Domain *string `json:"domain,omitempty"`
	// Organization website URL.
	Website *string `json:"website,omitempty"`
	// Organization description.
	Description *string `json:"description,omitempty"`
	// Primary industry classification.
	Industry *string `json:"industry,omitempty"`
	// List of sub-industry classifications.
	SubIndustries *[]string `json:"sub_industries,omitempty"`
	// Keywords associated with the organization.
	Keywords *[]string `json:"keywords,omitempty"`
	// Estimated number of employees.
	EstimatedNumEmployees *int `json:"estimated_num_employees,omitempty"`
	// Employee count range.
	EmployeeRange *string `json:"employee_range,omitempty"`
	// Annual revenue in USD.
	AnnualRevenue *float64 `json:"annual_revenue,omitempty"`
	// Revenue range description.
	RevenueRange *string `json:"revenue_range,omitempty"`
	// Country where the organization is based.
	Country *string `json:"country,omitempty"`
	// State or region.
	State *string `json:"state,omitempty"`
	// City where the organization is headquartered.
	City *string `json:"city,omitempty"`
	// Primary phone number.
	Phone *string `json:"phone,omitempty"`
	// Primary contact email.
	Email *string `json:"email,omitempty"`
	// LinkedIn company page URL.
	LinkedinURL *string `json:"linkedin_url,omitempty"`
	// Year the organization was founded.
	FoundedYear *int `json:"founded_year,omitempty"`
	// Whether the organization is publicly traded.
	PubliclyTraded *bool `json:"publicly_traded,omitempty"`
	// List of technologies used by the organization.
	Technologies *[]string `json:"technologies,omitempty"`
}

func (Organization) TargetModel() string { return "organization" }
