// Code generated by capmodelgen. DO NOT EDIT.

package capmodel

// Preseed is a capability model for Preseed.
type Preseed struct {
	// Type of the preseed data.
	Type string `json:"type"`
	// Title or category within the preseed type.
	Title string `json:"title"`
	// The actual preseed value.
	Value string `json:"value"`
	// Hint for UI display type (e.g., text, image, base64).
	Display string `json:"display"`
	// Capability associated with processing this preseed record.
	Capability string `json:"capability,omitempty"`
	// Additional metadata associated with the preseed record.
	Metadata map[string]string `json:"metadata,omitempty"`
	// User-provided comment about the preseed.
	Comment string `json:"comment,omitempty"`
}

func (Preseed) TargetModel() string { return "preseed" }
