// Code generated by capmodelgen. DO NOT EDIT.

package capmodel

// GCPResource is a capability model for GCPResource.
type GCPResource struct {
	IPs          []string       `json:"ips"`
	URLs         []string       `json:"urls"`
	Name         string         `json:"name"`
	DisplayName  string         `json:"displayName"`
	Provider     string         `json:"provider"`
	ResourceType string         `json:"resourceType"`
	Region       string         `json:"region"`
	AccountRef   string         `json:"accountRef"`
	Properties   map[string]any `json:"properties"`
	Labels       []string       `json:"labels"`
}

func (GCPResource) TargetModel() string { return "gcpresource" }
