// Code generated by capmodelgen. DO NOT EDIT.

package capmodel

import "encoding/json"

// Port is a capability model for Port.
type Port struct {
	Asset Asset `json:"-"`
	// The protocol of this port.
	Protocol string `json:"protocol"`
	// The port number of this port.
	Port int `json:"port"`
	// The name of the service identified on this port.
	Service string `json:"service"`
	// Capability that discovered this port.
	Capability string `json:"capability,omitempty"`
}

func (Port) TargetModel() string { return "port" }

// GetParentAsset returns the embedded parent asset for Port.
// The bool indicates whether to inject the parent into the child JSON.
func (s Port) GetParentAsset() (Asset, bool) { return s.Asset, true }

// Risk is a capability model for Risk.
type Risk struct {
	// Primary DNS or group associated with the risk.
	DNS string `json:"dns"`
	// Name of the risk or vulnerability.
	Name string `json:"name"`
	// User-provided comment about the risk.
	Comment string `json:"comment,omitempty"`
}

func (Risk) TargetModel() string { return "risk" }

// Technology is a capability model for Technology.
type Technology struct {
	// The full CPE string representation.
	CPE string `json:"cpe"`
	// Optional common name for the technology.
	Name string `json:"name,omitempty"`
	// User-provided comment about the technology record.
	Comment string `json:"comment,omitempty"`
}

func (Technology) TargetModel() string { return "technology" }

// Attribute is a capability model for Attribute.
type Attribute struct {
	Asset Asset `json:"-"`
	// Name of the attribute.
	Name string `json:"name"`
	// Value of the attribute.
	Value string `json:"value"`
	// Capability that discovered this attribute.
	Capability string `json:"capability,omitempty"`
	// Additional metadata associated with the attribute.
	Metadata map[string]string `json:"metadata,omitempty"`
}

func (Attribute) TargetModel() string { return "attribute" }

// GetParentAsset returns the embedded parent asset for Attribute.
// The bool indicates whether to inject the parent into the child JSON.
func (s Attribute) GetParentAsset() (Asset, bool) { return s.Asset, true }

// File is a capability model for File.
type File struct {
	// Name or path of the file.
	Name string `json:"name"`
	// File content. Must be a JSON-compatible string. Can be encoded with base64 if it begins with the prefix 'base64:'
	Bytes []byte `json:"bytes"`
}

func (File) TargetModel() string { return "file" }

// MarshalJSON implements json.Marshaler so that []byte fields are
// serialized as strings (matching SmartBytes behavior) instead of base64.
func (s File) MarshalJSON() ([]byte, error) {
	type alias File
	raw := struct {
		alias
		Bytes string `json:"bytes"`
	}{
		alias: alias(s),
		Bytes: string(s.Bytes),
	}
	return json.Marshal(raw)
}

// Webpage is a capability model for Webpage.
type Webpage struct {
	Asset Asset `json:"-"`
	// The basic URL of the webpage.
	URL string `json:"url"`
}

func (Webpage) TargetModel() string { return "webpage" }

// GetParentAsset returns the embedded parent asset for Webpage.
// The bool indicates whether to inject the parent into the child JSON.
func (s Webpage) GetParentAsset() (Asset, bool) { return s.Asset, false }

// WebApplication is a capability model for WebApplication.
type WebApplication struct {
	// The primary/canonical URL of the web application
	PrimaryURL string `json:"primary_url"`
	// Additional URLs associated with this web application
	URLs []string `json:"urls"`
	// Name of the web application
	Name string `json:"name"`
}

func (WebApplication) TargetModel() string { return "webapplication" }

// Preseed is a capability model for Preseed.
type Preseed struct {
	// Type of the preseed data.
	Type string `json:"type"`
	// Title or category within the preseed type.
	Title string `json:"title"`
	// The actual preseed value.
	Value string `json:"value"`
	// Hint for UI display type (e.g., text, image, base64).
	Display string `json:"display"`
	// Capability associated with processing this preseed record.
	Capability string `json:"capability,omitempty"`
	// Additional metadata associated with the preseed record.
	Metadata map[string]string `json:"metadata,omitempty"`
	// User-provided comment about the preseed.
	Comment string `json:"comment,omitempty"`
}

func (Preseed) TargetModel() string { return "preseed" }

// CloudResource is a capability model for CloudResource.
type CloudResource struct {
	IPs          []string       `json:"ips"`
	URLs         []string       `json:"urls"`
	Name         string         `json:"name"`
	DisplayName  string         `json:"displayName"`
	Provider     string         `json:"provider"`
	ResourceType string         `json:"resourceType"`
	Region       string         `json:"region"`
	AccountRef   string         `json:"accountRef"`
	Properties   map[string]any `json:"properties"`
	Labels       []string       `json:"labels"`
}

func (CloudResource) TargetModel() string { return "cloudresource" }

// AWSResource is a capability model for AWSResource.
type AWSResource struct {
	IPs               []string       `json:"ips"`
	URLs              []string       `json:"urls"`
	Name              string         `json:"name"`
	DisplayName       string         `json:"displayName"`
	Provider          string         `json:"provider"`
	ResourceType      string         `json:"resourceType"`
	Region            string         `json:"region"`
	AccountRef        string         `json:"accountRef"`
	Properties        map[string]any `json:"properties"`
	Labels            []string       `json:"labels"`
	OrgPolicyFilename string         `json:"orgPolicyFilename"`
}

func (AWSResource) TargetModel() string { return "awsresource" }

// AzureResource is a capability model for AzureResource.
type AzureResource struct {
	IPs           []string       `json:"ips"`
	URLs          []string       `json:"urls"`
	Name          string         `json:"name"`
	DisplayName   string         `json:"displayName"`
	Provider      string         `json:"provider"`
	ResourceType  string         `json:"resourceType"`
	Region        string         `json:"region"`
	AccountRef    string         `json:"accountRef"`
	Properties    map[string]any `json:"properties"`
	Labels        []string       `json:"labels"`
	ResourceGroup string         `json:"resourceGroup"`
}

func (AzureResource) TargetModel() string { return "azureresource" }

// GCPResource is a capability model for GCPResource.
type GCPResource struct {
	IPs          []string       `json:"ips"`
	URLs         []string       `json:"urls"`
	Name         string         `json:"name"`
	DisplayName  string         `json:"displayName"`
	Provider     string         `json:"provider"`
	ResourceType string         `json:"resourceType"`
	Region       string         `json:"region"`
	AccountRef   string         `json:"accountRef"`
	Properties   map[string]any `json:"properties"`
	Labels       []string       `json:"labels"`
}

func (GCPResource) TargetModel() string { return "gcpresource" }

// ADObject is a capability model for ADObject.
type ADObject struct {
	// Primary label of the object.
	Label string `json:"label"`
	// Secondary labels of the object.
	SecondaryLabels []string `json:"labels"`
	// AD domain this object belongs to.
	Domain string `json:"domain"`
	// Object identifier.
	ObjectID string `json:"objectid"`
	// Security identifier.
	SID string `json:"sid,omitempty"`
	// Common name of the AD object
	Name string `json:"name,omitempty"`
	// Descriptive text for the AD object
	Description string `json:"description,omitempty"`
	// Display name of the AD object
	DisplayName string `json:"displayname,omitempty"`
	// Indicates if object is protected by AdminSDHolder
	AdminCount bool `json:"admincount,omitempty"`
	// DNS hostname of the computer object
	DNSHostname string `json:"dnshostname,omitempty"`
	// Full distinguished name of the AD object
	DistinguishedName string `json:"distinguishedname,omitempty"`
	// Security identifier of the domain
	DomainSID string `json:"domainsid,omitempty"`
	// Account is marked as sensitive and cannot be delegated
	Sensitive bool `json:"sensitive,omitempty"`
	// Department the user belongs to
	Department string `json:"department,omitempty"`
	// Whether object has Service Principal Names registered
	HasSPN bool `json:"hasspn,omitempty"`
	// Account is trusted for unconstrained Kerberos delegation
	UnconstrainedDelegation bool `json:"unconstraineddelegation,omitempty"`
	// Last logon time in Windows NT time format
	LastLogon int64 `json:"lastlogon,omitempty"`
	// Whether Local Administrator Password Solution is enabled
	HasLAPS bool `json:"haslaps,omitempty"`
	// Kerberos pre-authentication is not required
	DontRequirePreAuth bool `json:"dontreqpreauth,omitempty"`
	// Password is set to never expire
	PasswordNeverExpires bool `json:"pwdneverexpires,omitempty"`
	// Domain or forest functional level
	FunctionalLevel string `json:"functionallevel,omitempty"`
	// Account is trusted for constrained delegation with protocol transition
	TrustedToAuth bool `json:"trustedtoauth,omitempty"`
	// Pre-Windows 2000 logon name
	SAMAccountName string `json:"samaccountname,omitempty"`
	// Whether computer is a Domain Controller
	IsDC bool `json:"isdc,omitempty"`
	// The service principal name(s) associated with this account
	ServicePrincipalNames []string `json:"serviceprincipalnames,omitempty"`
	// The operating system associated with this computer
	OperatingSystem string `json:"operatingsystem,omitempty"`
}

func (ADObject) TargetModel() string { return "adobject" }

// Person is a capability model for Person.
type Person struct {
	// Person's first name.
	FirstName *string `json:"first_name,omitempty"`
	// Person's last name.
	LastName *string `json:"last_name,omitempty"`
	// Person's full name.
	Name *string `json:"name,omitempty"`
	// Person's primary email address.
	Email *string `json:"email,omitempty"`
	// Person's current job title.
	Title *string `json:"title,omitempty"`
	// Person's professional headline.
	Headline *string `json:"headline,omitempty"`
	// Person's phone number.
	Phone *string `json:"phone,omitempty"`
	// List of personal email addresses.
	PersonalEmails *[]string `json:"personal_emails,omitempty"`
	// Person's work email address.
	WorkEmail *string `json:"work_email,omitempty"`
	// LinkedIn profile URL.
	LinkedinURL *string `json:"linkedin_url,omitempty"`
	// GitHub profile URL.
	GithubURL *string `json:"github_url,omitempty"`
	// Name of organization where person currently works.
	OrganizationName *string `json:"organization_name,omitempty"`
	// Email verification status.
	EmailStatus *string `json:"email_status,omitempty"`
	// Country where the person is located.
	Country *string `json:"country,omitempty"`
	// State or region where the person is located.
	State *string `json:"state,omitempty"`
	// City where the person is located.
	City *string `json:"city,omitempty"`
	// Seniority level.
	Seniority *string `json:"seniority,omitempty"`
	// List of departments person works in.
	Departments *[]string `json:"departments,omitempty"`
}

func (Person) TargetModel() string { return "person" }

// Organization is a capability model for Organization.
type Organization struct {
	// Organization name.
	Name *string `json:"name,omitempty"`
	// Primary domain associated with the organization.
	Domain *string `json:"domain,omitempty"`
	// Organization website URL.
	Website *string `json:"website,omitempty"`
	// Organization description.
	Description *string `json:"description,omitempty"`
	// Primary industry classification.
	Industry *string `json:"industry,omitempty"`
	// List of sub-industry classifications.
	SubIndustries *[]string `json:"sub_industries,omitempty"`
	// Keywords associated with the organization.
	Keywords *[]string `json:"keywords,omitempty"`
	// Estimated number of employees.
	EstimatedNumEmployees *int `json:"estimated_num_employees,omitempty"`
	// Employee count range.
	EmployeeRange *string `json:"employee_range,omitempty"`
	// Annual revenue in USD.
	AnnualRevenue *float64 `json:"annual_revenue,omitempty"`
	// Revenue range description.
	RevenueRange *string `json:"revenue_range,omitempty"`
	// Country where the organization is based.
	Country *string `json:"country,omitempty"`
	// State or region.
	State *string `json:"state,omitempty"`
	// City where the organization is headquartered.
	City *string `json:"city,omitempty"`
	// Primary phone number.
	Phone *string `json:"phone,omitempty"`
	// Primary contact email.
	Email *string `json:"email,omitempty"`
	// LinkedIn company page URL.
	LinkedinURL *string `json:"linkedin_url,omitempty"`
	// Year the organization was founded.
	FoundedYear *int `json:"founded_year,omitempty"`
	// Whether the organization is publicly traded.
	PubliclyTraded *bool `json:"publicly_traded,omitempty"`
	// List of technologies used by the organization.
	Technologies *[]string `json:"technologies,omitempty"`
}

func (Organization) TargetModel() string { return "organization" }
