// Code generated by capmodelgen. DO NOT EDIT.

package capmodel

// AWSResource is a capability model for AWSResource.
type AWSResource struct {
	IPs               []string       `json:"ips"`
	URLs              []string       `json:"urls"`
	Name              string         `json:"name"`
	DisplayName       string         `json:"displayName"`
	Provider          string         `json:"provider"`
	ResourceType      string         `json:"resourceType"`
	Region            string         `json:"region"`
	AccountRef        string         `json:"accountRef"`
	Properties        map[string]any `json:"properties"`
	Labels            []string       `json:"labels"`
	OrgPolicyFilename string         `json:"orgPolicyFilename"`
}

func (AWSResource) TargetModel() string { return "awsresource" }
