// Code generated by capmodelgen. DO NOT EDIT.

package capmodel

// ADObject is a capability model for ADObject.
type ADObject struct {
	// Primary label of the object.
	Label string `json:"label"`
	// Secondary labels of the object.
	SecondaryLabels []string `json:"labels"`
	// AD domain this object belongs to.
	Domain string `json:"domain"`
	// Object identifier.
	ObjectID string `json:"objectid"`
	// Security identifier.
	SID string `json:"sid,omitempty"`
	// Common name of the AD object
	Name string `json:"name,omitempty"`
	// Descriptive text for the AD object
	Description string `json:"description,omitempty"`
	// Display name of the AD object
	DisplayName string `json:"displayname,omitempty"`
	// Indicates if object is protected by AdminSDHolder
	AdminCount bool `json:"admincount,omitempty"`
	// DNS hostname of the computer object
	DNSHostname string `json:"dnshostname,omitempty"`
	// Full distinguished name of the AD object
	DistinguishedName string `json:"distinguishedname,omitempty"`
	// Security identifier of the domain
	DomainSID string `json:"domainsid,omitempty"`
	// Account is marked as sensitive and cannot be delegated
	Sensitive bool `json:"sensitive,omitempty"`
	// Department the user belongs to
	Department string `json:"department,omitempty"`
	// Whether object has Service Principal Names registered
	HasSPN bool `json:"hasspn,omitempty"`
	// Account is trusted for unconstrained Kerberos delegation
	UnconstrainedDelegation bool `json:"unconstraineddelegation,omitempty"`
	// Last logon time in Windows NT time format
	LastLogon int64 `json:"lastlogon,omitempty"`
	// Whether Local Administrator Password Solution is enabled
	HasLAPS bool `json:"haslaps,omitempty"`
	// Kerberos pre-authentication is not required
	DontRequirePreAuth bool `json:"dontreqpreauth,omitempty"`
	// Password is set to never expire
	PasswordNeverExpires bool `json:"pwdneverexpires,omitempty"`
	// Domain or forest functional level
	FunctionalLevel string `json:"functionallevel,omitempty"`
	// Account is trusted for constrained delegation with protocol transition
	TrustedToAuth bool `json:"trustedtoauth,omitempty"`
	// Pre-Windows 2000 logon name
	SAMAccountName string `json:"samaccountname,omitempty"`
	// Whether computer is a Domain Controller
	IsDC bool `json:"isdc,omitempty"`
	// The service principal name(s) associated with this account
	ServicePrincipalNames []string `json:"serviceprincipalnames,omitempty"`
	// The operating system associated with this computer
	OperatingSystem string `json:"operatingsystem,omitempty"`
}

func (ADObject) TargetModel() string { return "adobject" }
