// Code generated by capmodelgen. DO NOT EDIT.

package capmodel

// Port is a capability model for Port.
type Port struct {
	Asset Asset `json:"-"`
	// The protocol of this port.
	Protocol string `json:"protocol"`
	// The port number of this port.
	Port int `json:"port"`
	// The name of the service identified on this port.
	Service string `json:"service"`
	// Capability that discovered this port.
	Capability string `json:"capability,omitempty"`
}

func (Port) TargetModel() string { return "port" }

// GetParentAsset returns the embedded parent asset for Port.
// The bool indicates whether to inject the parent into the child JSON.
func (s Port) GetParentAsset() (Asset, bool) { return s.Asset, true }
