// Code generated by capmodelgen. DO NOT EDIT.

package capmodel

// Webpage is a capability model for Webpage.
type Webpage struct {
	Asset Asset `json:"-"`
	// The basic URL of the webpage.
	URL string `json:"url"`
}

func (Webpage) TargetModel() string { return "webpage" }

// GetParentAsset returns the embedded parent asset for Webpage.
// The bool indicates whether to inject the parent into the child JSON.
func (s Webpage) GetParentAsset() (Asset, bool) { return s.Asset, false }
