// Code generated by capmodelgen. DO NOT EDIT.

package capmodel

// Technology is a capability model for Technology.
type Technology struct {
	// The full CPE string representation.
	CPE string `json:"cpe"`
	// Optional common name for the technology.
	Name string `json:"name,omitempty"`
	// User-provided comment about the technology record.
	Comment string `json:"comment,omitempty"`
}

func (Technology) TargetModel() string { return "technology" }
