// Code generated by capmodelgen. DO NOT EDIT.

package capmodel

// Risk is a capability model for Risk.
type Risk struct {
	// Primary DNS or group associated with the risk.
	DNS string `json:"dns"`
	// Name of the risk or vulnerability.
	Name string `json:"name"`
	// User-provided comment about the risk.
	Comment string `json:"comment,omitempty"`
}

func (Risk) TargetModel() string { return "risk" }
