// Code generated by capmodelgen. DO NOT EDIT.

package capmodel

// Attribute is a capability model for Attribute.
type Attribute struct {
	Asset Asset `json:"-"`
	// Name of the attribute.
	Name string `json:"name"`
	// Value of the attribute.
	Value string `json:"value"`
	// Capability that discovered this attribute.
	Capability string `json:"capability,omitempty"`
	// Additional metadata associated with the attribute.
	Metadata map[string]string `json:"metadata,omitempty"`
}

func (Attribute) TargetModel() string { return "attribute" }

// GetParentAsset returns the embedded parent asset for Attribute.
// The bool indicates whether to inject the parent into the child JSON.
func (s Attribute) GetParentAsset() (Asset, bool) { return s.Asset, true }
