// Code generated by capmodelgen. DO NOT EDIT.

package capmodel

import "encoding/json"

// File is a capability model for File.
type File struct {
	// Name or path of the file.
	Name string `json:"name"`
	// File content. Must be a JSON-compatible string. Can be encoded with base64 if it begins with the prefix 'base64:'
	Bytes []byte `json:"bytes"`
}

func (File) TargetModel() string { return "file" }

// MarshalJSON implements json.Marshaler so that []byte fields are
// serialized as strings (matching SmartBytes behavior) instead of base64.
func (s File) MarshalJSON() ([]byte, error) {
	type alias File
	raw := struct {
		alias
		Bytes string `json:"bytes"`
	}{
		alias: alias(s),
		Bytes: string(s.Bytes),
	}
	return json.Marshal(raw)
}
