// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

type ADObject struct {
	Label    string `json:"label"`
	Domain   string `json:"domain"`
	ObjectID string `json:"objectid"`
}

func (s ADObject) Convert() (*model.ADObject, error) {
	m := make(map[string]any)
	m["label"] = s.Label
	m["domain"] = s.Domain
	m["objectid"] = s.ObjectID

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.ADObject
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

type AWSResource struct {
	IPs          []string       `json:"ips"`
	URLs         []string       `json:"urls"`
	Name         string         `json:"name"`
	ResourceType string         `json:"resourceType"`
	Region       string         `json:"region"`
	Properties   map[string]any `json:"properties"`
}

func (s AWSResource) Convert() (*model.AWSResource, error) {
	m := make(map[string]any)
	m["ips"] = s.IPs
	m["urls"] = s.URLs
	m["name"] = s.Name
	m["resourceType"] = s.ResourceType
	m["region"] = s.Region
	m["properties"] = s.Properties

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.AWSResource
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

type Asset struct {
	DNS  string `json:"dns"`
	Name string `json:"name"`
}

func (s Asset) Convert() (*model.Asset, error) {
	m := make(map[string]any)
	m["dns"] = s.DNS
	m["name"] = s.Name

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Asset
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

type AzureResource struct {
	IPs          []string       `json:"ips"`
	URLs         []string       `json:"urls"`
	Name         string         `json:"name"`
	ResourceType string         `json:"resourceType"`
	Region       string         `json:"region"`
	Properties   map[string]any `json:"properties"`
}

func (s AzureResource) Convert() (*model.AzureResource, error) {
	m := make(map[string]any)
	m["ips"] = s.IPs
	m["urls"] = s.URLs
	m["name"] = s.Name
	m["resourceType"] = s.ResourceType
	m["region"] = s.Region
	m["properties"] = s.Properties

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.AzureResource
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

type CloudResource struct {
	IPs          []string       `json:"ips"`
	URLs         []string       `json:"urls"`
	Name         string         `json:"name"`
	ResourceType string         `json:"resourceType"`
	Region       string         `json:"region"`
	Properties   map[string]any `json:"properties"`
}

func (s CloudResource) Convert() (*model.CloudResource, error) {
	m := make(map[string]any)
	m["ips"] = s.IPs
	m["urls"] = s.URLs
	m["name"] = s.Name
	m["resourceType"] = s.ResourceType
	m["region"] = s.Region
	m["properties"] = s.Properties

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.CloudResource
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

type Domain struct {
	DNS string `json:"domain"`
}

func (s Domain) Convert() (*model.Asset, error) {
	m := make(map[string]any)
	m["dns"] = s.DNS
	m["name"] = s.DNS

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Asset
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

type File struct {
	Name  string `json:"name"`
	Bytes []byte `json:"bytes"`
}

func (s File) Convert() (*model.File, error) {
	m := make(map[string]any)
	m["name"] = s.Name
	m["bytes"] = s.Bytes

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.File
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

type GCPResource struct {
	IPs          []string       `json:"ips"`
	URLs         []string       `json:"urls"`
	Name         string         `json:"name"`
	ResourceType string         `json:"resourceType"`
	Region       string         `json:"region"`
	Properties   map[string]any `json:"properties"`
}

func (s GCPResource) Convert() (*model.GCPResource, error) {
	m := make(map[string]any)
	m["ips"] = s.IPs
	m["urls"] = s.URLs
	m["name"] = s.Name
	m["resourceType"] = s.ResourceType
	m["region"] = s.Region
	m["properties"] = s.Properties

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.GCPResource
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

type IP struct {
	DNS string `json:"ip"`
}

func (s IP) Convert() (*model.Asset, error) {
	m := make(map[string]any)
	m["dns"] = s.DNS
	m["name"] = s.DNS

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Asset
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

type Organization struct {
	Name    *string `json:"name"`
	Domain  *string `json:"domain"`
	Website *string `json:"website"`
}

func (s Organization) Convert() (*model.Organization, error) {
	m := make(map[string]any)
	m["name"] = s.Name
	m["domain"] = s.Domain
	m["website"] = s.Website

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Organization
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

type Person struct {
	FirstName *string `json:"first_name"`
	LastName  *string `json:"last_name"`
	Name      *string `json:"name"`
	Email     *string `json:"email"`
	Title     *string `json:"title"`
}

func (s Person) Convert() (*model.Person, error) {
	m := make(map[string]any)
	m["first_name"] = s.FirstName
	m["last_name"] = s.LastName
	m["name"] = s.Name
	m["email"] = s.Email
	m["title"] = s.Title

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Person
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

type Port struct {
	Protocol string `json:"protocol"`
	Port     int    `json:"port"`
	Service  string `json:"service"`
	Parent   Asset  `json:"parent"`
}

func (s Port) Convert() (*model.Port, error) {
	m := make(map[string]any)
	m["protocol"] = s.Protocol
	m["port"] = s.Port
	m["service"] = s.Service
	parentModel, err := s.Parent.Convert()
	if err != nil {
		return nil, err
	}

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Port
	result.Defaulted()
	if err := json.Unmarshal(b, &result); err != nil {
		return nil, err
	}
	result.Parent = model.NewGraphModelWrapper(parentModel)
	if err := registry.CallHooks(&result); err != nil {
		return nil, err
	}

	return &result, nil
}

type Preseed struct {
	Type  string `json:"type"`
	Title string `json:"title"`
	Value string `json:"value"`
}

func (s Preseed) Convert() (*model.Preseed, error) {
	m := make(map[string]any)
	m["type"] = s.Type
	m["title"] = s.Title
	m["value"] = s.Value

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Preseed
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

type Risk struct {
	DNS    string `json:"dns"`
	Name   string `json:"name"`
	Source string `json:"source"`
	Status string `json:"status"`
	Target Asset  `json:"target"`
}

func (s Risk) Convert() (*model.Risk, error) {
	m := make(map[string]any)
	m["dns"] = s.DNS
	m["name"] = s.Name
	m["source"] = s.Source
	m["status"] = s.Status
	parentModel, err := s.Target.Convert()
	if err != nil {
		return nil, err
	}

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Risk
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}
	result.Target = parentModel

	return &result, nil
}

type Technology struct {
	CPE  string `json:"cpe"`
	Name string `json:"name"`
}

func (s Technology) Convert() (*model.Technology, error) {
	m := make(map[string]any)
	m["cpe"] = s.CPE
	m["name"] = s.Name

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Technology
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

type WebApplication struct {
	PrimaryURL string   `json:"primary_url"`
	URLs       []string `json:"urls"`
	Name       string   `json:"name"`
}

func (s WebApplication) Convert() (*model.WebApplication, error) {
	m := make(map[string]any)
	m["primary_url"] = s.PrimaryURL
	m["urls"] = s.URLs
	m["name"] = s.Name

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.WebApplication
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

type Webpage struct {
	URL    string         `json:"url"`
	Parent WebApplication `json:"parent"`
}

func (s Webpage) Convert() (*model.Webpage, error) {
	m := make(map[string]any)
	m["url"] = s.URL
	parentModel, err := s.Parent.Convert()
	if err != nil {
		return nil, err
	}

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Webpage
	result.Defaulted()
	if err := json.Unmarshal(b, &result); err != nil {
		return nil, err
	}
	result.Parent = parentModel
	if err := registry.CallHooks(&result); err != nil {
		return nil, err
	}

	return &result, nil
}
