// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

// ADObject is a capability model for model.ADObject.
type ADObject struct {
	Label    string `json:"label"`
	Domain   string `json:"domain"`
	ObjectID string `json:"objectid"`
}

// Convert converts this capability model to a full model.ADObject.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s ADObject) Convert() (*model.ADObject, error) {
	m := make(map[string]any)
	m["label"] = s.Label
	m["domain"] = s.Domain
	m["objectid"] = s.ObjectID

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.ADObject
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

// AWSResource is a capability model for model.AWSResource.
type AWSResource struct {
	IPs          []string       `json:"ips"`
	URLs         []string       `json:"urls"`
	Name         string         `json:"name"`
	ResourceType string         `json:"resourceType"`
	Region       string         `json:"region"`
	Properties   map[string]any `json:"properties"`
}

// Convert converts this capability model to a full model.AWSResource.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s AWSResource) Convert() (*model.AWSResource, error) {
	m := make(map[string]any)
	m["ips"] = s.IPs
	m["urls"] = s.URLs
	m["name"] = s.Name
	m["resourceType"] = s.ResourceType
	m["region"] = s.Region
	m["properties"] = s.Properties

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.AWSResource
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

// Asset is a capability model for model.Asset.
type Asset struct {
	DNS  string `json:"dns"`
	Name string `json:"name"`
}

// Convert converts this capability model to a full model.Asset.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s Asset) Convert() (*model.Asset, error) {
	m := make(map[string]any)
	m["dns"] = s.DNS
	m["name"] = s.Name

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.Asset
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

// Attribute is a capability model for model.Attribute.
type Attribute struct {
	Name   string `json:"name"`
	Value  string `json:"value"`
	Parent Asset  `json:"parent"`
}

// Convert converts this capability model to a full model.Attribute.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s Attribute) Convert() (*model.Attribute, error) {
	m := make(map[string]any)
	m["name"] = s.Name
	m["value"] = s.Value
	parentModel, err := s.Parent.Convert()
	if err != nil {
		return nil, err
	}

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	// For types with injected parents, we unmarshal without hooks first,
	// set the parent, then call hooks (which may depend on the parent).
	var result model.Attribute
	result.Defaulted()
	if err := json.Unmarshal(b, &result); err != nil {
		return nil, err
	}
	result.Parent = model.NewGraphModelWrapper(parentModel)
	if err := registry.CallHooks(&result); err != nil {
		return nil, err
	}

	return &result, nil
}

// AzureResource is a capability model for model.AzureResource.
type AzureResource struct {
	IPs          []string       `json:"ips"`
	URLs         []string       `json:"urls"`
	Name         string         `json:"name"`
	ResourceType string         `json:"resourceType"`
	Region       string         `json:"region"`
	Properties   map[string]any `json:"properties"`
}

// Convert converts this capability model to a full model.AzureResource.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s AzureResource) Convert() (*model.AzureResource, error) {
	m := make(map[string]any)
	m["ips"] = s.IPs
	m["urls"] = s.URLs
	m["name"] = s.Name
	m["resourceType"] = s.ResourceType
	m["region"] = s.Region
	m["properties"] = s.Properties

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.AzureResource
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

// CloudResource is a capability model for model.CloudResource.
type CloudResource struct {
	IPs          []string       `json:"ips"`
	URLs         []string       `json:"urls"`
	Name         string         `json:"name"`
	ResourceType string         `json:"resourceType"`
	Region       string         `json:"region"`
	Properties   map[string]any `json:"properties"`
}

// Convert converts this capability model to a full model.CloudResource.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s CloudResource) Convert() (*model.CloudResource, error) {
	m := make(map[string]any)
	m["ips"] = s.IPs
	m["urls"] = s.URLs
	m["name"] = s.Name
	m["resourceType"] = s.ResourceType
	m["region"] = s.Region
	m["properties"] = s.Properties

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.CloudResource
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

// Domain is a capability model for model.Asset.
type Domain struct {
	DNS string `json:"domain"`
}

// Convert converts this capability model to a full model.Asset.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s Domain) Convert() (*model.Asset, error) {
	m := make(map[string]any)
	m["dns"] = s.DNS
	m["name"] = s.DNS

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.Asset
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

// File is a capability model for model.File.
type File struct {
	Name  string `json:"name"`
	Bytes []byte `json:"bytes"`
}

// Convert converts this capability model to a full model.File.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s File) Convert() (*model.File, error) {
	m := make(map[string]any)
	m["name"] = s.Name
	m["bytes"] = s.Bytes

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.File
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

// GCPResource is a capability model for model.GCPResource.
type GCPResource struct {
	IPs          []string       `json:"ips"`
	URLs         []string       `json:"urls"`
	Name         string         `json:"name"`
	ResourceType string         `json:"resourceType"`
	Region       string         `json:"region"`
	Properties   map[string]any `json:"properties"`
}

// Convert converts this capability model to a full model.GCPResource.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s GCPResource) Convert() (*model.GCPResource, error) {
	m := make(map[string]any)
	m["ips"] = s.IPs
	m["urls"] = s.URLs
	m["name"] = s.Name
	m["resourceType"] = s.ResourceType
	m["region"] = s.Region
	m["properties"] = s.Properties

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.GCPResource
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

// IP is a capability model for model.Asset.
type IP struct {
	DNS string `json:"ip"`
}

// Convert converts this capability model to a full model.Asset.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s IP) Convert() (*model.Asset, error) {
	m := make(map[string]any)
	m["dns"] = s.DNS
	m["name"] = s.DNS

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.Asset
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

// Organization is a capability model for model.Organization.
type Organization struct {
	Name    *string `json:"name"`
	Domain  *string `json:"domain"`
	Website *string `json:"website"`
}

// Convert converts this capability model to a full model.Organization.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s Organization) Convert() (*model.Organization, error) {
	m := make(map[string]any)
	m["name"] = s.Name
	m["domain"] = s.Domain
	m["website"] = s.Website

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.Organization
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

// Person is a capability model for model.Person.
type Person struct {
	FirstName *string `json:"first_name"`
	LastName  *string `json:"last_name"`
	Name      *string `json:"name"`
	Email     *string `json:"email"`
	Title     *string `json:"title"`
}

// Convert converts this capability model to a full model.Person.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s Person) Convert() (*model.Person, error) {
	m := make(map[string]any)
	m["first_name"] = s.FirstName
	m["last_name"] = s.LastName
	m["name"] = s.Name
	m["email"] = s.Email
	m["title"] = s.Title

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.Person
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

// Port is a capability model for model.Port.
type Port struct {
	Protocol string `json:"protocol"`
	Port     int    `json:"port"`
	Parent   Asset  `json:"parent"`
}

// Convert converts this capability model to a full model.Port.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s Port) Convert() (*model.Port, error) {
	m := make(map[string]any)
	m["protocol"] = s.Protocol
	m["port"] = s.Port
	parentModel, err := s.Parent.Convert()
	if err != nil {
		return nil, err
	}

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	// For types with injected parents, we unmarshal without hooks first,
	// set the parent, then call hooks (which may depend on the parent).
	var result model.Port
	result.Defaulted()
	if err := json.Unmarshal(b, &result); err != nil {
		return nil, err
	}
	result.Parent = model.NewGraphModelWrapper(parentModel)
	if err := registry.CallHooks(&result); err != nil {
		return nil, err
	}

	return &result, nil
}

// Preseed is a capability model for model.Preseed.
type Preseed struct {
	Type  string `json:"type"`
	Title string `json:"title"`
	Value string `json:"value"`
}

// Convert converts this capability model to a full model.Preseed.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s Preseed) Convert() (*model.Preseed, error) {
	m := make(map[string]any)
	m["type"] = s.Type
	m["title"] = s.Title
	m["value"] = s.Value

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.Preseed
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

// Risk is a capability model for model.Risk.
type Risk struct {
	DNS    string `json:"dns"`
	Name   string `json:"name"`
	Source string `json:"source"`
	Status string `json:"status"`
	Target Asset  `json:"target"`
}

// Convert converts this capability model to a full model.Risk.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s Risk) Convert() (*model.Risk, error) {
	m := make(map[string]any)
	m["dns"] = s.DNS
	m["name"] = s.Name
	m["source"] = s.Source
	m["status"] = s.Status
	parentModel, err := s.Target.Convert()
	if err != nil {
		return nil, err
	}

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.Risk
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}
	result.Target = parentModel

	return &result, nil
}

// Technology is a capability model for model.Technology.
type Technology struct {
	CPE string `json:"cpe"`
}

// Convert converts this capability model to a full model.Technology.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s Technology) Convert() (*model.Technology, error) {
	m := make(map[string]any)
	m["cpe"] = s.CPE

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.Technology
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

// WebApplication is a capability model for model.WebApplication.
type WebApplication struct {
	PrimaryURL string   `json:"primary_url"`
	URLs       []string `json:"urls"`
	Name       string   `json:"name"`
}

// Convert converts this capability model to a full model.WebApplication.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s WebApplication) Convert() (*model.WebApplication, error) {
	m := make(map[string]any)
	m["primary_url"] = s.PrimaryURL
	m["urls"] = s.URLs
	m["name"] = s.Name

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.WebApplication
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}

// Webpage is a capability model for model.Webpage.
type Webpage struct {
	URL    string         `json:"url"`
	Parent WebApplication `json:"parent"`
}

// Convert converts this capability model to a full model.Webpage.
// It applies defaults and hooks via registry.UnmarshalModel.
func (s Webpage) Convert() (*model.Webpage, error) {
	m := make(map[string]any)
	m["url"] = s.URL

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var result model.Webpage
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}
	converted, err := s.Parent.Convert()
	if err != nil {
		return nil, err
	}
	result.Parent = converted
	if err := registry.CallHooks(&result); err != nil {
		return nil, err
	}

	return &result, nil
}
