// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

type Organization struct {
	Name    *string `json:"name"`
	Domain  *string `json:"domain"`
	Website *string `json:"website"`
}

func (s Organization) Convert() (*model.Organization, error) {
	m := make(map[string]any)
	m["name"] = s.Name
	m["domain"] = s.Domain
	m["website"] = s.Website

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Organization
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}
