// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

type Person struct {
	FirstName *string `json:"first_name"`
	LastName  *string `json:"last_name"`
	Name      *string `json:"name"`
	Email     *string `json:"email"`
	Title     *string `json:"title"`
}

func (s Person) Convert() (*model.Person, error) {
	m := make(map[string]any)
	m["first_name"] = s.FirstName
	m["last_name"] = s.LastName
	m["name"] = s.Name
	m["email"] = s.Email
	m["title"] = s.Title

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Person
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}
