// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

type Port struct {
	Protocol string `json:"protocol"`
	Port     int    `json:"port"`
	Service  string `json:"service"`
	Parent   Asset  `json:"parent"`
}

func (s Port) Convert() (*model.Port, error) {
	m := make(map[string]any)
	m["protocol"] = s.Protocol
	m["port"] = s.Port
	m["service"] = s.Service
	parentModel, err := s.Parent.Convert()
	if err != nil {
		return nil, err
	}

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Port
	result.Defaulted()
	if err := json.Unmarshal(b, &result); err != nil {
		return nil, err
	}
	result.Parent = model.NewGraphModelWrapper(parentModel)
	if err := registry.CallHooks(&result); err != nil {
		return nil, err
	}

	return &result, nil
}
