// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

type Risk struct {
	Name   string `json:"name"`
	Source string `json:"source"`
	Status string `json:"status"`
	Target Asset  `json:"target"`
}
