// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

// ModelType maps each capmodel type name to the model type name its converter produces.
// For example, "Domain" maps to "Asset" because capmodel.Domain converts to model.Asset.
var ModelType = map[string]string{
	"ADObject":       "ADObject",
	"AWSResource":    "AWSResource",
	"Asset":          "Asset",
	"AzureResource":  "AzureResource",
	"Domain":         "Asset",
	"File":           "File",
	"GCPResource":    "GCPResource",
	"IP":             "Asset",
	"Organization":   "Organization",
	"Person":         "Person",
	"Port":           "Port",
	"Preseed":        "Preseed",
	"Risk":           "Risk",
	"Technology":     "Technology",
	"WebApplication": "WebApplication",
	"Webpage":        "Webpage",
}
