// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

type WebApplication struct {
	PrimaryURL string   `json:"primary_url"`
	URLs       []string `json:"urls"`
	Name       string   `json:"name"`
}

func (s WebApplication) Convert() (*model.WebApplication, error) {
	m := make(map[string]any, 3)
	m["primary_url"] = s.PrimaryURL
	m["urls"] = s.URLs
	m["name"] = s.Name

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.WebApplication
	if err := registry.UnmarshalModel(b, &result); err != nil {
		return nil, err
	}

	return &result, nil
}
