// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"encoding/json"

	"github.com/praetorian-inc/tabularium/pkg/model/model"
	"github.com/praetorian-inc/tabularium/pkg/registry"
)

type Webpage struct {
	URL    string         `json:"url"`
	Parent WebApplication `json:"parent"`
}

func (s Webpage) Convert() (*model.Webpage, error) {
	m := make(map[string]any, 1)
	m["url"] = s.URL
	parentModel, err := s.Parent.Convert()
	if err != nil {
		return nil, err
	}

	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result model.Webpage
	result.Defaulted()
	if err := json.Unmarshal(b, &result); err != nil {
		return nil, err
	}
	result.Parent = parentModel
	if err := registry.CallHooks(&result); err != nil {
		return nil, err
	}

	return &result, nil
}
