// Code generated by capmodelgen; DO NOT EDIT.

package models

type AzureResource struct {
	IPs           []string       `json:"ips"`
	URLs          []string       `json:"urls"`
	Name          string         `json:"name"`
	ResourceType  string         `json:"resourceType"`
	Region        string         `json:"region"`
	AccountRef    string         `json:"accountRef"`
	Properties    map[string]any `json:"properties"`
	ResourceGroup string         `json:"resourceGroup"`
}
