// Code generated by capmodelgen; DO NOT EDIT.

package models

type Organization struct {
	Name                  *string    `json:"name"`
	Domain                *string    `json:"domain"`
	Website               *string    `json:"website"`
	Description           *string    `json:"description"`
	Industry              *string    `json:"industry"`
	SubIndustries         *[]string  `json:"sub_industries"`
	Keywords              *[]string  `json:"keywords"`
	OrganizationType      *string    `json:"organization_type"`
	BusinessModel         *string    `json:"business_model"`
	EstimatedNumEmployees *int       `json:"estimated_num_employees"`
	EmployeeRange         *string    `json:"employee_range"`
	AnnualRevenue         *float64   `json:"annual_revenue"`
	RevenueRange          *string    `json:"revenue_range"`
	MarketCapitalization  *float64   `json:"market_capitalization"`
	Country               *string    `json:"country"`
	State                 *string    `json:"state"`
	City                  *string    `json:"city"`
	PostalCode            *string    `json:"postal_code"`
	StreetAddress         *string    `json:"street_address"`
	Phone                 *string    `json:"phone"`
	Fax                   *string    `json:"fax"`
	Email                 *string    `json:"email"`
	LinkedinURL           *string    `json:"linkedin_url"`
	TwitterURL            *string    `json:"twitter_url"`
	FacebookURL           *string    `json:"facebook_url"`
	BlogURL               *string    `json:"blog_url"`
	FoundedYear           *int       `json:"founded_year"`
	PubliclyTraded        *bool      `json:"publicly_traded"`
	TickerSymbol          *string    `json:"ticker_symbol"`
	Exchange              *string    `json:"exchange"`
	Technologies          *[]string  `json:"technologies"`
	TechCategories        *[]string  `json:"tech_categories"`
	TechVendors           *[]string  `json:"tech_vendors"`
	AlternatePhones       *[]string  `json:"alternate_phones"`
	PhoneTypes            *[]string  `json:"phone_types"`
	FundingRounds         *[]string  `json:"funding_rounds"`
	FundingAmounts        *[]float64 `json:"funding_amounts"`
	Investors             *[]string  `json:"investors"`
	AdditionalAddresses   *[]string  `json:"additional_addresses"`
	AddressTypes          *[]string  `json:"address_types"`
}
