// Code generated by capmodelgen; DO NOT EDIT.

package models

type Person struct {
	FirstName        *string   `json:"first_name"`
	LastName         *string   `json:"last_name"`
	Name             *string   `json:"name"`
	Email            *string   `json:"email"`
	Title            *string   `json:"title"`
	Headline         *string   `json:"headline"`
	Phone            *string   `json:"phone"`
	PersonalEmails   *[]string `json:"personal_emails"`
	WorkEmail        *string   `json:"work_email"`
	LinkedinURL      *string   `json:"linkedin_url"`
	TwitterURL       *string   `json:"twitter_url"`
	FacebookURL      *string   `json:"facebook_url"`
	GithubURL        *string   `json:"github_url"`
	PhotoURL         *string   `json:"photo_url"`
	OrganizationName *string   `json:"organization_name"`
	Country          *string   `json:"country"`
	State            *string   `json:"state"`
	City             *string   `json:"city"`
	Seniority        *string   `json:"seniority"`
	Departments      *[]string `json:"departments"`
	Functions        *[]string `json:"functions"`
}
