// Code generated by capmodelgen; DO NOT EDIT.

package models

type Repository struct {
	LastScanState map[string]string `json:"lastScanState"`
	URL           string            `json:"url"`
	Org           string            `json:"org"`
	Name          string            `json:"name"`
	Public        bool              `json:"public"`
}
