// Code generated by capmodelgen; DO NOT EDIT.

package models

type Risk struct {
	Name   string `json:"name"`
	Source string `json:"source"`
	Status string `json:"status"`
	Proof  []byte `json:"proof"`
	Target Asset  `json:"target"`
}
