// Code generated by capmodelgen; DO NOT EDIT.

package models

type Risk struct {
	DNS    string `json:"dns"`
	Name   string `json:"name"`
	Source string `json:"source"`
	Status string `json:"status"`
	Target Asset  `json:"target"`
}
